name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Lint
        run: |
          cd backend
          npm run lint
      - name: Run tests with coverage
        run: |
          cd backend
          npm test 
      - name: Upload coverage to Coveralls
        if: success()
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DB_HOST: shortline.proxy.rlwy.net
      DB_PORT: 50471
      DB_USER: postgres
      DB_PASSWORD: ropCGaheBshmtwhUeevKJxJzUANWNkOb
      DB_NAME: railway
      JWT_SECRET: ac82e1662cf49d86e87921c8bd343ef6cb7a2ad6f6c51d297254ffa59236512076bb576a7af647c98470ba56a452620f73dbe138875c164bc7bad1fc43917f93
      REFRESH_TOKEN: 1187fa458cf6c72397070ce7bf886415c4c8202ff7aaf3afd4d7cb7097a69f0e263dcf3777d5690be42b0b1c90089e342806e2c5e9a329247fce0caffb8b6dcc